services:
  postgres:
    container_name: 'team-peoli-postgres'
    image: bitnami/postgresql:16
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres:/bitnami/postgresql
    networks:
      - team-peoli
    env_file:
      - .env
    restart: on-failure
  api:
    container_name: 'team-peoli-api'
    build: .
    ports:
      - '3000:3000'
    networks:
      - team-peoli
    depends_on:
      - postgres
    restart: no

networks:
  team-peoli:
