services:
  postgres:
    container_name: 'team-peoli-postgres'
    image: bitnami/postgresql:16
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres:/bitnami/postgresql
    env_file:
      - .env
    restart: on-failure
  api:
    container_name: 'team-peoli-api'
    image: 851725455120.dkr.ecr.sa-east-1.amazonaws.com/team-peoli:latest
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    restart: on-failure
