services:
  postgres:
    container_name: 'team-peoli-postgres'
    image: bitnami/postgresql:16
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres:/bitnami/postgresql
    env_file:
      - .env
    restart: on-failure
    networks:
      - team-peoli
  api:
    container_name: 'team-peoli-api'
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - team-peoli

networks:
  team-peoli:
    driver: bridge
