name: Docker Image CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Copy files to the right path
        run: rsync --remove-source-files -r ./ /home/admin/api
      - name: Build docker image
        working-directory: /home/admin/api
        run: docker buildx build . --tag team-peoli-api
      - name: Run image
        run: docker run --name team-peoli-api team-peoli-api
      - name: Clean up
        working-directory: /home/admin/api
        run: ls | grep -xvE ".docker|.env" | xargs rm -r
